# 设置最大请求和文件上传大小
spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 服务端口
server:
  port: 18082

# eureka 客户端信息配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

# 自定义 fastdfs 服务器地址信息
fastdfs-server:
  ip: 192.168.100.100
  port: 8080