server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dogbro_mall_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Aa123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  # token存储到redis的过期时间
  clientId: DogBro  # 客户端id 用户登录auth
  clientSecret: Aa123456 # 客户端密钥
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/dogbro.jks     # 证书路径
    secret: Aa123456    # 证书密钥
    alias: DogBro       # 证书别名
    password: Aa123456    # 证书密码