server:
  port: 18088
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dogbro_mall_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Aa123456
  redis:
    host: 127.0.0.1
    port: 6379
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

# 开启feign的熔断机制，默认是线程池隔离
feign:
  hystrix:
    enabled: true
# 使用信号量隔离 解决 开启feign的熔断机制的时候，feign拦截器无法获取请求头问题
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

#MQ配置支付交换机和队列
mq:
  pay:
    exchange:
      order: exchange.order   # 发送的交换机
    queue:
      order: queue.order    # 队列名称
    routing:
      key: queue.order